"""Veridian language-server client (LSP over stdio).

Veridian is a SystemVerilog/Verilog language server. Unlike vhdl_ls it
takes no command-line arguments: it reads a ``veridian.yaml`` (or
``veridian.yml``) from its working directory, which the client starts
in the repository root. A repository-provided config is respected and
left in place; a ``veridian_hook`` shell command may generate one;
only as a fallback does the client write a built-in default (removed
again on shutdown).

The built-in config declares the repository root as the workdir and as
include/source roots, so `` `include`` files and `` `define`` macros
resolve within the tree being indexed.

Veridian's diagnostics carry no diagnostic codes (they come from
slang), so the syntax-error predicate is severity-based: severity 1 is
an Error. Veridian's documentSymbol tree uses plain names and standard
LSP SymbolKinds (module/program 2, package 4, function 12, variable
13, property 7, interface 11, TypeParameter 26 for parameters);
``always_*`` blocks and generate blocks are not reported at all, and
tasks appear as unnamed Function entries (recovered from the source
line by the chunker).
"""

from __future__ import annotations

from .client import LspClient

#: ``veridian.yaml`` keys are case-sensitive; ``log_level`` accepts
#: exactly Error/Warn/Info/Debug/Trace.
DEFAULT_VERIDIAN_CONFIG = """\
# Generated by corvidex-mcp (removed when the session ends).
auto_search_workdir: true
include_dirs:
  - .
source_dirs:
  - .
log_level: Warn
"""


class VeridianLsp(LspClient):
    """Veridian client: no extra args, a ``veridian.yaml`` workspace config."""

    language_id = "verilog"
    config_name = "veridian.yaml"

    # slang diagnostics have no code field; severity 1 is an Error
    # (parse errors included), 2 a warning, 3 a hint. That matches the
    # base class's severity-based default, so no override is needed
    # here.

    def default_config_text(self) -> str | None:
        return DEFAULT_VERIDIAN_CONFIG
